server:
  port: 8081
spring:
  application:
    name: gateway-demo
  cloud:
    consul:
      host: http://127.0.0.1 # consul 注册地址
      port: 8500
      discovery:
          prefer-ip-address: true
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/gateway?useUnicode=true&characterEncoding=UTF-8
     username: root
     password: root





# 路由策略,配置文件
zuul:
  routes:
#    # mics-name: /user/**
#
    user:
      path: /user1/**
      url: http://127.0.0.1:8080
      #serviceId: 1
management:
  security:
    enabled: false
      #strip-prefix: false
